### PR TITLE
ETHRelay to refund lost tokens

### PR DESCRIPTION
**Pull request by jchen217**
in response to UniswapV3 issue #583 
https://github.com/Uniswap/v3-core/issues/583

### CODE REVIEW

**Review by truestorybaby — APPROVED** [review]

**Review by truestorybaby — APPROVED** [review]

**Review by truestorybaby — APPROVED** [review]

**Comment by Talynlove22** [comment]
pull request stop stealing tlove

**Comment by Erik4569** [comment]
Request stop

**Review by mas722 — APPROVED** [review]

**Comment by Roob0910** [comment]
Rquest stop

**Comment by Roob0910** [comment]
Request stop

**Review by Muniz-colima — APPROVED** [review]

**Review by truestorybaby — APPROVED** [review]

**Review by truestorybaby — APPROVED** [review]

**Review by truestorybaby — APPROVED** [review]

**Review by Erik4569 — APPROVED** [review]

**Comment by Erik4569** [comment]
Hi

**Comment by Erik4569** [comment]
contracts/Ethash.sol

**Review by Erik4569 — APPROVED** [review]
@jchen217 4AEE18F83AFDEB23

**Comment by ewilz** [comment]
pools function as intended.

**Comment by jchen217** [comment]
> pools function as intended.

@ewilz Hi, thank you for your time!
Sorry but I don't understand what do you mean. Is the pool contract is updated. Can the locked token be returned now?

**Pull request closed without merging**
